### ISSUE TITLE
Rescue POD gets emptied of resources

### ISSUE THREAD

**Issue by Will565** [Will565/IFI-Life-Support#9]
Rescue contracts empty resources from pod causing LS system to kill kerbal

**Comment by VladRassokhin** [comment]
See similar code in TACLS: https://github.com/taraniselsu/TacLifeSupport/commit/e5a1e40e40e1f70869d3ad8254996c4f4f01dd62
The main idea is to store list of known vessels and add some resources into new founded.

**Comment by afchacon** [comment]
taraniselsu's solution looks quite simple - this might be added in [IFILifeSupport/LifeSupportTracking.cs#L258](https://github.com/Will565/IFI-Life-Support/blob/master/IFILifeSupport/LifeSupportTracking.cs#L258)

I might be wrong here - and ignore me if I am - but it appears to be that the problem with applying this directly would make the vessel recover all of its LS after it has depleted. So the check for if the vessel is a rescue mission or not (via tac's method) would have to be placed in a more general (when loaded) part of code rather than when the resource gets used.

basically inject into [IFILifeSupport/LifeSupportTracking.cs#L111](https://github.com/Will565/IFI-Life-Support/blob/master/IFILifeSupport/LifeSupportTracking.cs#L111) the check for if it is a known crew member and immediately reload the LS amount in  [IFILifeSupport/LifeSupportTracking.cs#L115](https://github.com/Will565/IFI-Life-Support/blob/master/IFILifeSupport/LifeSupportTracking.cs#L115) and add that crew to the known crew 

Disclaimer: First time looking at this code! - just my two cents :)
(I'll gladly help with anything if you ask! - this particular problem was making me wonder how the whole addon stuff works on ksp though)

**Comment by Will565** [comment]
Thanks for help, testing right now, and with a few tweaks this looks like it will work

**Comment by Will565** [comment]
fixed with 2.7 release
